spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_task_manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml